### ISSUE TITLE
Checking project #3

### ISSUE THREAD

**Issue by No-answerday** [No-answerday/Fibonachicken#3]
## Task list

- [ ] 서버 정상작동 확인
- [ ] 알고리즘 코드 확인
- [ ] 디자인 진행상황 확인
